layout_spectrum: 1
name: Live is a trip
title: Escrevendo o livro de nossa historia
collections:
  - index:
      paginate: true
      path: /
      number: 15
      navigable: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 0.5776966
  lightness: 0.9131535
  saturation: 0.3364249
  rhythmicContrast: 0.3903879
  brandColors:
    - '#391A43'
    - '#D6BF96'
    - '#5C4152'
    - '#DE8B69'
    - '#D55A3C'
typography_spectrum: 0.4745347
